# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: mobigo
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  mailpit:
    extends:
      file: ./mailpit.yml
      service: mailpit
